Upgrade rails to the latest 3.2
This fixes the error:

NoMethodError: undefined method `name' for nil:NilClass
/home/openfoodnetwork/my_store/db/seeds.rb:10:in `<top (required)>'
/home/openfoodnetwork/.rbenv/versions/2.2.7/bin/bundle:23:in `load'
/home/openfoodnetwork/.rbenv/versions/2.2.7/bin/bundle:23:in `<main>'

when running `bundle exec rake db:seed`. This is due to
https://github.com/rails/rails/issues/21316